export const ADDFAVORITES = "ADDFAVORITES";
export const REMOVEFAVORITES = "REMOVEFAVORITES";
export const FILTER = "FILTER";
export const ORDER = "ORDER";
export const GETFAVORITES = "GETFAVORITES";
export const LEAVEFAVORITES = "LEAVEFAVORITES";
export const RESETFAVORITES = "RESETFAVORITES";
