export const ADDFAVORITES = "ADDFAVORITES";
export const REMOVEFAVORITES = "REMOVEFAVORITES";
export const FILTER = "FILTER";
export const ORDER = "ORDER";
export const GETFAVORITES = "GETFAVORITES";
export const RESETFAVORITES = "RESETFAVORITES";
export const LOGINUSER = "LOGINUSER";
export const PERSISTENTUSER = "PERSISTENTUSER";
